#!/usr/bin/env python

from kmexpert.cli import cli


def init_procedures():
    # import here all relevant procedures
    import example_procedure


if __name__ == '__main__':
    init_procedures()
    cli()
